version: '3'
services:
    app:
        container_name: education
        build:
            context: .docker/php
            dockerfile: Dockerfile
        volumes:
        - ./:/var/www
        working_dir: /var/www
    redis:
        container_name: redis
        image: 'redis'
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        networks:
            - app
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - pgsql
    node:
        container_name: nodeJS
        build:
            context: .docker/node
            dockerfile: Dockerfile
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
                    - .:/var/www # Монтируем локальную папку в контейнер как /var/ww
        networks:
            - app
    pgsql:
        container_name: pgsql
        image: 'postgres'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - ./.docker/postgresql/data:/var/lib/postgresql/data

networks:
    app:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local

